routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', 'HomeController@index')->name('welcome');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/search', 'HomeController@search')->name('search');
Route::get('/place/details/{id}', 'HomeController@placeDdetails')->name('place.details');
Route::get('/package/details/{id}', 'HomeController@packageDetails')->name('package.details');
Route::get('/place-list', 'HomeController@allPlace')->name('all.place');
Route::get('/package-list', 'HomeController@allPackage')->name('all.package');
Route::get('/district/{id}', 'HomeController@districtWisePlace')->name('district.wise.place');
Route::get('/placetype/{id}', 'HomeController@placetypeWisePlace')->name('placetype.wise.place');

Route::get('/package/booking/{id}', 'HomeController@packageBooking')->name('package.booking');
Route::get('/package/booking', 'HomeController@storeBookingRequest')->name('store.package.booking');

Auth::routes(['verify' => true]);

// Route::get('/home', 'HomeController@index')->name('home');

Route::group([
    'as' => 'admin.',
    'prefix' => 'admin',
    'namespace' => 'Admin',
    'middleware' => [
        'auth', 'admin', 'verified',
    ],
], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    Route::get('profile-info', 'DashboardController@showProfile')->name('profile.show');
    Route::get('profile-info/edit/{id}', 'DashboardController@editProfile')->name('profile.edit');
    Route::post('profile-info/update', 'DashboardController@updateProfile')->name('profile.update');

    Route::resource('district', 'DistrictController');
    Route::resource('type', 'TypeController');
    Route::resource('place', 'PlaceController');
    Route::resource('about', 'AboutController');
    Route::resource('guide', 'GuideController');
    Route::resource('users', 'UsersController');
    Route::resource('package', 'PackageController');
    Route::get('list', 'UsersController@adminList')->name('list');

    Route::resource('slides', 'SliderController');

    Route::get('booking-request/list', 'BookingController@pendingBookingList')->name('pending.booking');
    Route::post('booking-request/approve/{id}', 'BookingController@bookingApprove')->name('booking.approve');
    Route::post('booking-request/remove/{id}', 'BookingController@bookingRemoveByAdmin')->name('booking.remove');
    Route::get('running/packages/', 'BookingController@runningPackage')->name('package.running');
    Route::post('running/package/complete/{id}', 'BookingController@runningPackageComplete')->name('package.running.complete');
    Route::get('tour-history/list', 'BookingController@tourHistory')->name('tour.history');
});

Route::group([
    'as' => 'user.',
    'prefix' => 'user',
    'namespace' => 'User',
    'middleware' => [
        'auth', 'user', 'verified',
    ],
], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    Route::get('profile-info', 'DashboardController@showProfile')->name('profile.show');
    Route::get('profile-info/edit/{id}', 'DashboardController@editProfile')->name('profile.edit');
    Route::post('profile-info/update', 'DashboardController@updateProfile')->name('profile.update');

    Route::get('districts', 'DashboardController@getDistrict')->name('district');
    Route::get('placetypes', 'DashboardController@getPlaceType')->name('placetype');

    Route::get('places', 'DashboardController@getPlaces')->name('place');
    Route::get('places/{id}', 'DashboardController@getPlaceDetails')->name('place.show');

    Route::get('guides', 'DashboardController@getGuides')->name('guide');
    Route::get('guide/{id}', 'DashboardController@getGuideDetails')->name('guide.show');

    Route::get('packages', 'DashboardController@getPackage')->name('package');
    Route::get('packages/{id}', 'DashboardController@getPackageDetails')->name('package.show');

    Route::get('tour-history/list', 'BookingController@tourHistory')->name('tour.history');
    Route::get('booking-request/list', 'BookingController@pendingBookingList')->name('pending.booking');
    Route::post('booking-request/cancel/{id}', 'BookingController@canceLBookingRequest')->name('booking.cancel');
});

View::composer('layouts.frontend.inc.footer', function ($view) {
    $placetypes = App\Placetype::all();
    $view->with('placetypes', $placetypes);
});

app/Guide.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Guide extends Model
{
    public function bookings(){
        return $this->hasMany(Booking::class);
    }
}

app/Http/Controllers/Admin/GuideController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Guide;
use App\Http\Controllers\Controller;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;

class GuideController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $guides = Guide::latest()->paginate(8);
        $guideCount = Guide::all()->count();
        return view('admin.guide.index', compact('guides', 'guideCount'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('admin.guide.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'nid' => 'required|unique:guides|numeric',
            'email' => 'required|unique:guides|email',
            'contact' => 'required|unique:guides|numeric',
            'address' => 'required',
            'image' => 'required|mimes:jpeg,png,jpg',

        ]);

        // Get Form Image
        $image = $request->file('image');

        if (isset($image)) {

            // Make Unique Name for Image
            $currentDate = Carbon::now()->toDateString();
            $imageName = $currentDate . '-' . uniqid() . '.' . $image->getClientOriginalExtension();

            // Check Category Dir is exists

            if (!Storage::disk('public')->exists('guide')) {
                Storage::disk('public')->makeDirectory('guide');
            }

            // Resize Image for category and upload
            $GuideImage = Image::make($image)->resize(180, 210)->stream();
            Storage::disk('public')->put('guide/' . $imageName, $GuideImage);

        } else {
            $imageName = "default.png";
        }

        $guide = new Guide();
        //$students->user_id = Auth::id();
        $guide->name = $request->name;

        $guide->nid = $request->nid;
        $guide->image = $imageName;
        $guide->email = $request->email;
        $guide->contact = $request->contact;
        $guide->address = $request->address;
        $guide->save();
        return redirect(route('admin.guide.index'))->with('success', 'Guide Inserted Successfully');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Guide $guide)
    {

        return view('admin.guide.show', compact('guide'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Guide $guide)
    {

        return view('admin.guide.edit', compact('guide'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $guide = Guide::find($id);
        $this->validate($request, [
            'name' => 'required',
            'nid' => 'required|numeric|unique:guides,nid,' . $guide->id,
            'email' => 'required|email|unique:guides,email,' . $guide->id,
            'contact' => 'required|numeric|unique:guides,contact,' . $guide->id,
            'address' => 'required',
            'image' => 'mimes:jpeg,png,jpg|image',
        ]);

        // Get Form Image
        $image = $request->file('image');
        if (isset($image)) {
            // Make Unique Name for Image
            $currentDate = Carbon::now()->toDateString();
            $imageName = $currentDate . '-' . uniqid() . '.' . $image->getClientOriginalExtension();

            // Check Category Dir is exists
            if (!Storage::disk('public')->exists('guide')) {
                Storage::disk('public')->makeDirectory('guide');
            }

            // Delete old post image
            if (Storage::disk('public')->exists('guide/' . $guide->image)) {
                Storage::disk('public')->delete('guide/' . $guide->image);
            }

            // Resize Image for category and upload
            $GuideImage = Image::make($image)->resize(180, 210)->stream();
            Storage::disk('public')->put('guide/' . $imageName, $GuideImage);

        } else {
            $imageName = $guide->image;
        }

        $guide->name = $request->name;
        $guide->nid = $request->nid;
        $guide->image = $imageName;
        $guide->email = $request->email;
        $guide->contact = $request->contact;
        $guide->address = $request->address;
        $guide->save();
        return redirect(route('admin.guide.index'))->with('success', 'Guide Updated Successfully');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Guide $guide)
    {

        // Delete image
        if (Storage::disk('public')->exists('guide/' . $guide->image)) {
            Storage::disk('public')->delete('guide/' . $guide->image);
        }

        $guide->delete();

        return redirect(route('admin.guide.index'))->with('success', 'Guide deleted Successfully');
    }
}

resources/views/admin/guide/create.blade.php
@extends('layouts.backend.master')
@section('title')
Desa Wisata Lantan - Guide Add
@endsection
@section('content')

<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-9">
			<div class="card mt-5">
				<div class="card-header  bg-dark">
					<h3 class="card-title float-left"><strong>Create Guide</strong></h3>

				</div>
				<!-- /.card-header -->
				<div class="card-body">



					@include('partial.errors')

					<form action="{{ route('admin.guide.store') }}" method="POST" enctype="multipart/form-data">
						@csrf
						<div class="form-group">
							<label for="name"> Name: </label>
							<input type="text" class="form-control" placeholder="Enter Name" id="name" name="name">
						</div>
						<div class="form-group">
							<label for="nid"> Nid: </label>
							<input type="text" class="form-control" placeholder="Enter Nid" id="nid" name="nid">
						</div>
						<div class="form-group">
							<label for="email"> Email: </label>
							<input type="text" class="form-control" placeholder="Enter Email " id="email" name="email">
						</div>
						<div class="form-group">
							<label for="contact"> Contact: </label>
							<input type="text" class="form-control" placeholder="Enter Contact" id="contact"
								name="contact">
						</div>
						<div class="form-group">
							<label for="address"> Address: </label>
							<input type="text" class="form-control" placeholder="Enter Address" id="address"
								name="address">
						</div>
						<div class="form-group">
							<label for="image"> Image: </label>
							<input type="file" class="form-control" id="image" name="image">
						</div>

						<div class="form-group">
							<button type="submit" class="btn btn-success">Create</button>
							<a href="{{ URL::previous() }}" class="btn btn-danger wave-effect">Back</a>
						</div>


					</form>


				</div>

				<!-- /.card-body -->
			</div>
			<!-- /.card -->
		</div>
	</div>
</div><!-- /.container -->





@endsection

resources/views/admin/guide/edit.blade.php
@extends('layouts.backend.master')
@section('title')
Desa Wisata Lantan - Guide Edit
@endsection
@section('content')
<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-9">
			<div class="card mt-5">
				<div class="card-header bg-dark">
					<h3 class="card-title float-left"><strong>Update Guide</strong></h3>

				</div>
				<!-- /.card-header -->
				<div class="card-body">
					@include('partial.errors')
					<form action="{{ route('admin.guide.update',$guide->id) }}" method="POST"
						enctype="multipart/form-data">
						@csrf
						@method('PUT')

						<div class="form-group">
							<label for="name"> Name: </label>
							<input type="text" class="form-control" placeholder="Enter Guide Name" id="name" name="name"
								value="{{ old('name',$guide->name) }}">
						</div>


						<div class="form-group">
							<label for="nid"> Nid: </label>
							<input type="text" class="form-control" placeholder="Enter Guide nid" id="nid" name="nid"
								value="{{old('nid',$guide->nid) }}">
						</div>

						<div class="form-group">
							<label for="email"> Email: </label>
							<input type="text" class="form-control" placeholder="Enter Email " id="email" name="email"
								value="{{old('email',$guide->email)}}">
						</div>

						<div class="form-group">
							<label for="contact"> Contact: </label>
							<input type="text" class="form-control" placeholder="Enter Contact" id="contact"
								name="contact" value="{{old('contact',$guide->contact)}}">
						</div>

						<div class="form-group">
							<label for="address"> Address: </label>
							<input type="text" class="form-control" placeholder="Enter address" id="address"
								name="address" value="{{old('address',$guide->address)}}">
						</div>

						<div class="form-group">
							<label for="image"> Image: </label>
							<input type="file" class="form-control" id="image" name="image">
						</div>

						<div class="form-group">
							<label for="image"> Old Image</label>
							<img src="{{ asset('storage/guide/'.$guide->image) }}" height="80px;" width="60px;">
						</div>


						<div class="form-group">
							<button type="submit" class="btn btn-success">Update</button>
							<a href="{{ URL::previous() }}" class="btn btn-danger wave-effect">Back</a>
						</div>

					</form>


				</div>

				<!-- /.card-body -->
			</div>
			<!-- /.card -->
		</div>
	</div>
</div><!-- /.container -->
@endsection

resources/views/admin/guide/index.blade.php
@extends('layouts.backend.master')
@section('title')
Desa Wisata Lantan - Guide
@endsection
@section('content')
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-12">

      @include('partial.successMessage')

      <div class="card my-5 mx-4">
        <div class="card-header  bg-dark">
          <h3 class="card-title float-left p-0 m-0"><strong>Manage Guide ({{ $guideCount }})</strong></h3>
          <a href="{{route('admin.guide.create')}}" class="btn btn-success btn-md float-right c-white">Add New <i
              class="fa fa-plus"></i></a>
        </div>
        <!-- card-header -->
        @if ($guides->count() > 0)
        <div class="card-body">
          <div class="table-responsive">
            <table id="dataTableId" class="table table-bordered table-striped">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Email</th>
                  <th>Contact</th>
                  <th>image</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                @foreach ($guides as $key=>$guide)
                <tr>
                  <td>{{ $guide->name }}</td>
                  <td>{{ $guide->email }}</td>
                  <td>{{ $guide->contact }}</td>
                  <td>
                    <img style="height: 70px; width: 60px;" class="img-fluid"
                      src="{{ asset('storage/guide/'.$guide->image) }}" alt="image">
                  </td>
                  <td>
                    <a href="{{ route('admin.guide.show', $guide->id) }}" class="btn btn-success">Details</a>

                    <a href="{{ route('admin.guide.edit', $guide->id) }}" class="btn btn-info">Edit</a>

                    <button type="submit" onclick="handleDeleteGuide( {{ $guide->id }}) "
                      class="btn btn-danger">Delete</button>
                  </td>
                </tr>
                @endforeach
              </tbody>
            </table>
          </div>

          <!-- Modal -->
          <div class="modal fade" id="deleteGuideModal" tabindex="-1" aria-labelledby="exampleModalLabel"
            aria-hidden="true">
            <div class="modal-dialog">
              <form action="" id="deleteGuideForm" method="POST">
                @csrf
                @method('DELETE')
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Guide Delete</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <div class="text-center">Are you sure to delete this Guide?</div>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-success" data-dismiss="modal">No, Go Back</button>
                    <button type="submit" class="btn btn-danger">Yes, Delete</button>
                  </div>
                </div>
              </form>
            </div>
          </div>

        </div>
        @else
        <h2 class="text-center text-info font-weight-bold m-3">No Guide Found</h2>
        @endif
        <div class="pagination">
          {{ $guides->links() }}
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
  </div>
</div><!-- /.container -->
@endsection

@section('scripts')
<script>
  function handleDeleteGuide(id){

          var form = document.getElementById('deleteGuideForm')
          form.action = 'guide/' + id 
          $('#deleteGuideModal').modal('show')
          //console.log(form)
       }
</script>
@endsection

resources/views/admin/guide/show.blade.php
@extends('layouts.backend.master')
@section('title')
Desa Wisata Lantan - show
@endsection
@section('content')

<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-6 m-5">
			<div class="card">
				<div class="card-header bg-info"><strong>Details</strong></div>
				<div class="card-body">
					<table class="table">
						<tr>
							<th></th>
							<td><img class="img-fluid" style="border-radius: 10%;border:2px solid rgb(110, 110, 110);"
									src="{{ asset('storage/guide/'.$guide->image) }}" alt="image"></td>
						</tr>
						<tr>
							<th>Name</th>
							<td>{{ $guide->name }}</td>
						</tr>
						<tr>
							<th>Email</th>
							<td>{{ $guide->email }}</td>
						</tr>
						<tr>
							<th>Contact</th>
							<td>{{ $guide->contact }}</td>
						</tr>
						<tr>
							<th>Nid</th>
							<td>{{ $guide->nid }}</td>
						</tr>
						<tr>
							<th>Address</th>
							<td>{{ $guide->address }}</td>
						</tr>
					</table>
				</div>
				<div class="card-footer">
					<a href="{{ route('admin.guide.edit', $guide->id) }}" class="btn btn-info">Edit</a>
					<a href="{{ route('admin.guide.index') }}" class="btn btn-danger">Back</a>
				</div>
			</div>
		</div>
	</div>
</div>


@endsection