routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', 'HomeController@index')->name('welcome');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/search', 'HomeController@search')->name('search');
Route::get('/place/details/{id}', 'HomeController@placeDdetails')->name('place.details');
Route::get('/package/details/{id}', 'HomeController@packageDetails')->name('package.details');
Route::get('/place-list', 'HomeController@allPlace')->name('all.place');
Route::get('/package-list', 'HomeController@allPackage')->name('all.package');
Route::get('/district/{id}', 'HomeController@districtWisePlace')->name('district.wise.place');
Route::get('/placetype/{id}', 'HomeController@placetypeWisePlace')->name('placetype.wise.place');

Route::get('/package/booking/{id}', 'HomeController@packageBooking')->name('package.booking');
Route::get('/package/booking', 'HomeController@storeBookingRequest')->name('store.package.booking');

Auth::routes(['verify' => true]);

// Route::get('/home', 'HomeController@index')->name('home');

Route::group([
    'as' => 'admin.',
    'prefix' => 'admin',
    'namespace' => 'Admin',
    'middleware' => [
        'auth', 'admin', 'verified',
    ],
], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    Route::get('profile-info', 'DashboardController@showProfile')->name('profile.show');
    Route::get('profile-info/edit/{id}', 'DashboardController@editProfile')->name('profile.edit');
    Route::post('profile-info/update', 'DashboardController@updateProfile')->name('profile.update');

    Route::resource('district', 'DistrictController');
    Route::resource('type', 'TypeController');
    Route::resource('place', 'PlaceController');
    Route::resource('about', 'AboutController');
    Route::resource('guide', 'GuideController');
    Route::resource('users', 'UsersController');
    Route::resource('package', 'PackageController');
    Route::get('list', 'UsersController@adminList')->name('list');

    Route::resource('slides', 'SliderController');

    Route::get('booking-request/list', 'BookingController@pendingBookingList')->name('pending.booking');
    Route::post('booking-request/approve/{id}', 'BookingController@bookingApprove')->name('booking.approve');
    Route::post('booking-request/remove/{id}', 'BookingController@bookingRemoveByAdmin')->name('booking.remove');
    Route::get('running/packages/', 'BookingController@runningPackage')->name('package.running');
    Route::post('running/package/complete/{id}', 'BookingController@runningPackageComplete')->name('package.running.complete');
    Route::get('tour-history/list', 'BookingController@tourHistory')->name('tour.history');
});

Route::group([
    'as' => 'user.',
    'prefix' => 'user',
    'namespace' => 'User',
    'middleware' => [
        'auth', 'user', 'verified',
    ],
], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    Route::get('profile-info', 'DashboardController@showProfile')->name('profile.show');
    Route::get('profile-info/edit/{id}', 'DashboardController@editProfile')->name('profile.edit');
    Route::post('profile-info/update', 'DashboardController@updateProfile')->name('profile.update');

    Route::get('districts', 'DashboardController@getDistrict')->name('district');
    Route::get('placetypes', 'DashboardController@getPlaceType')->name('placetype');

    Route::get('places', 'DashboardController@getPlaces')->name('place');
    Route::get('places/{id}', 'DashboardController@getPlaceDetails')->name('place.show');

    Route::get('guides', 'DashboardController@getGuides')->name('guide');
    Route::get('guide/{id}', 'DashboardController@getGuideDetails')->name('guide.show');

    Route::get('packages', 'DashboardController@getPackage')->name('package');
    Route::get('packages/{id}', 'DashboardController@getPackageDetails')->name('package.show');

    Route::get('tour-history/list', 'BookingController@tourHistory')->name('tour.history');
    Route::get('booking-request/list', 'BookingController@pendingBookingList')->name('pending.booking');
    Route::post('booking-request/cancel/{id}', 'BookingController@canceLBookingRequest')->name('booking.cancel');
});

View::composer('layouts.frontend.inc.footer', function ($view) {
    $placetypes = App\Placetype::all();
    $view->with('placetypes', $placetypes);
});

app/District.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class District extends Model
{
    public function places(){
        return $this->hasMany(Place::class);
    }
}

app/Http/Controllers/Admin/DistrictController.php
<?php

namespace App\Http\Controllers\Admin;

use App\District;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DistrictController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $districts = District::latest()->paginate(8);
        $districtcount = District::all()->count();
        return view('admin.district.index', compact('districts', 'districtcount'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.district.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|unique:districts',
        ]);

        $districts = new District();
        $districts->name = $request->name;
        $districts->save();

        return redirect(route('admin.district.index'))->with('success', 'District name inserted successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(District $district)
    {

        return view('admin.district.edit', compact('district'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $districts = District::find($id);
        $this->validate($request, [
            'name' => 'required|unique:districts,name,' . $districts->id,
        ]);

        $districts->name = $request->name;
        $districts->save();

        return redirect(route('admin.district.index'))->with('success', 'District Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(District $district)
    {
        if ($district->places->count() > 0) {
            return redirect()->back()->with('danger', 'District cannot be deleted, because it has some places');
        }

        $district->delete();
        return redirect(route('admin.district.index'))->with('success', 'District deleted Successfully');
    }
}

resources/views/admin/district/create.blade.php
@extends('layouts.backend.master')
@section('title')
Desa Wisata Lantan - Create District
@endsection
@section('content')

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-9">
      <div class="card mt-5">
        <div class="card-header  bg-dark">
          <h3 class="card-title float-left"><strong>Create District</strong></h3>

        </div>
        <!-- /.card-header -->
        <div class="card-body">



          @include('partial.errors')

          <form action="{{ route('admin.district.store') }}" method="POST">
            @csrf
            <div class="form-group">
              <label for="name"> Name: </label>
              <input type="text" class="form-control" placeholder="Enter District Name" id="name" name="name">
            </div>

            <div class="form-group">
              <button type="submit" class="btn btn-success">Create</button>
              <a href="{{ URL::previous() }}" class="btn btn-danger wave-effect">Back</a>
            </div>


          </form>


        </div>

        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
  </div>
</div><!-- /.container -->





@endsection

resources/views/admin/district/edit.blade.php
@extends('layouts.backend.master')
@section('title')
Desa Wisata Lantan - Edit District
@endsection
@section('content')
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-9">
      <div class="card mt-5">
        <div class="card-header  bg-dark">
          <h3 class="card-title float-left"><strong>Update District</strong></h3>

        </div>
        <!-- /.card-header -->
        <div class="card-body">
          @include('partial.errors')
          <form action="{{ route('admin.district.update',$district->id) }}" method="POST">
            @csrf
            @method('PUT')

            <div class="form-group">
              <label for="name"> Name: </label>
              <input type="text" class="form-control" placeholder="Enter District Name" id="name" name="name"
                value="{{ old('name',$district->name) }}">
            </div>


            <div class="form-group">
              <button type="submit" class="btn btn-success">Update</button>
              <a href="{{ URL::previous() }}" class="btn btn-danger wave-effect">Back</a>
            </div>

          </form>


        </div>

        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
  </div>
</div><!-- /.container -->
@endsection

resources/views/admin/district/index.blade.php
@extends('layouts.backend.master')
@section('title')
Desa Wisata Lantan - District
@endsection
@section('content')


<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-9">

      @include('partial.successMessage')

      <div class="card mt-5">
        <div class="card-header  bg-dark">
          <h3 class="card-title float-left p-0 m-0"><strong>Manage District ({{ $districtcount }})</strong></h3>
          <a href="{{route('admin.district.create')}}" class="btn btn-success btn-md float-right c-white">Add New <i
              class="fa fa-plus"></i></a>
        </div>
        <!-- card-header -->
        @if ($districts->count() > 0)
        <div class="card-body">
          <div class="table-responsive">
            <table id="dataTableId" class="table table-bordered table-striped">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Added</th>
                  <th>Place Count</th>
                  <th width="25%">Action</th>
                </tr>
              </thead>
              <tbody>
                @foreach ($districts as $key=>$district)
                <tr>
                  <td>{{ $district->name }}</td>
                  <td>{{ $district->created_at->toFormattedDateString() }}</td>
                  <td>{{ $district->places->count() }}</td>
                  <td>
                    <a href="{{ route('admin.district.edit', $district->id) }}" class="btn btn-info">Edit</a>
                    <button type="submit" onclick="handleDeleteDistrict( {{ $district->id }}) "
                      class="btn btn-danger">Delete</button>
                  </td>
                </tr>
                @endforeach
              </tbody>
            </table>
          </div>

          <!-- Modal -->
          <div class="modal fade" id="deleteDistrictModal" tabindex="-1" aria-labelledby="exampleModalLabel"
            aria-hidden="true">
            <div class="modal-dialog">
              <form action="" id="deleteDistrictForm" method="POST">
                @csrf
                @method('DELETE')
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">District Delete</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <div class="text-center">Are you sure to delete this district?</div>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-success" data-dismiss="modal">No, Go Back</button>
                    <button type="submit" class="btn btn-danger">Yes, Delete</button>
                  </div>
                </div>
              </form>
            </div>
          </div>

        </div>
        @else
        <h2 class="text-center text-info font-weight-bold m-3">No District Found</h2>
        @endif
        <div class="pagination">
          {{ $districts->links() }}
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
  </div>
</div><!-- /.container -->
@endsection

@section('scripts')
<script>
  function handleDeleteDistrict(id){

          var form = document.getElementById('deleteDistrictForm')
          form.action = 'district/' + id 
          $('#deleteDistrictModal').modal('show')
          //console.log(form)
       }
</script>
@endsection